name: travisgautier

services:
  postgres:
    image: postgres:18-alpine
    container_name: travisgautier-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-travisgautier}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev}
      POSTGRES_DB: ${POSTGRES_DB:-travisgautier}
    ports:
      - '5432:5432'
    volumes:
      - travisgautier-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-travisgautier}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  travisgautier-postgres-data:
